# There no language TeX
language: c
install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-extra poppler-utils
  - gem install bundler
  - bundle update
script: make fancytabs.pdf && make check
after_success:
  # Only deploy when tag matches VERSION
  - grep -q "VERSION\s*=\s*${TRAVIS_BRANCH}$" Makefile && sudo apt-get install texlive-extra-utils libwww-mechanize-perl
  - grep -q "VERSION\s*=\s*${TRAVIS_BRANCH}$" Makefile && make upload
